export const data = {
  products: [
    {
      name: 'Nike Shoe',
      slug: 'nike-shoe',
      category: 'shirt',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 100,
      brand: 'Nike',
      reating: 4.5,
      numReview: 10,
      description: 'Higt qulity',
    },
    {
      name: 'Nike shirt',
      slug: 'nike-shirt',
      category: 'shirt',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 100,
      brand: 'Nike',
      reating: 4.5,
      numReview: 10,
      description: 'Higt qulity',
    },
    {
      name: 'clvin Shoe',
      slug: 'clvin-shoe',
      category: 'shirt',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 100,
      brand: 'Nike',
      reating: 4.5,
      numReview: 10,
      description: 'Higt qulity',
    },
    {
      name: 'usa Shoe',
      slug: 'usa-shoe',
      category: 'shirt',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 100,
      brand: 'Nike',
      reating: 4.5,
      numReview: 10,
      description: 'Higt qulity',
    },
  ],
};
